name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build Docker image
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
          TAG=$(echo "${GITHUB_REF#refs/tags/}")
          docker build -t raeckelboomp/t-nsa-800_sample-app:$TAG .
      
      - name: Push Docker image to Docker Hub
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
          TAG=$(echo "${GITHUB_REF#refs/tags/}")
          docker push raeckelboomp/t-nsa-800_sample-app:$TAG
  
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    if: github.event_name == 'workflow_dispatch' && success()
    # The deployment job will run either manually triggered or after successful tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Connect to target server
        uses: appleboy/ssh-action@master
        with:
          host: app-web527358.westeurope.cloudapp.azure.com
          username: admuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull latest Docker image
        run: docker pull raeckelboomp/t-nsa-800_sample-app:latest
      
      - name: Copy docker-compose.yml to server
        run: scp -o StrictHostKeyChecking=no docker-compose.yml admuser@app-web527358.westeurope.cloudapp.azure.com:/app/docker-compose.yml
      
      - name: Restart containers with Docker Compose
        run: ssh -o StrictHostKeyChecking=no admuser@app-web527358.westeurope.cloudapp.azure.com "cd /app && docker-compose up -d"
