name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build Docker image
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
          TAG=$(echo "${GITHUB_REF#refs/tags/}")
          docker build -t raeckelboomp/t-nsa-800_sample-app:$TAG .
      
      - name: Push Docker image to Docker Hub
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
          TAG=$(echo "${GITHUB_REF#refs/tags/}")
          docker push raeckelboomp/t-nsa-800_sample-app:$TAG
