name: Deploy

on:
  workflow_dispatch:
      inputs:
        tag:
          description: 'Docker image tag'
          required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: 'master'
      
      - name: Connect to target server
        uses: appleboy/ssh-action@master
        with:
          host: app-web527358.westeurope.cloudapp.azure.com
          username: admuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSWORD }}

      - name: Pull latest Docker image
        run: docker pull raeckelboomp/t-nsa-800_sample-app:${{ github.event.inputs.tag }}

      - name: List directory
        run: ls

      - name: Prepare the docker-compose tar.
        run: |
          mkdir temp
          cp docker-compose.yaml temp/
          tar -cvf deploy.tar ./temp

      - name: Copy docker-compose.yaml to server
        uses: appleboy/scp-action@master
        with:
          host: app-web527358.westeurope.cloudapp.azure.com
          username: admuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSWORD }}
          source: "deploy.tar"
          target: /home/admuser/app
        
      - name: Restart containers with Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: app-web527358.westeurope.cloudapp.azure.com
          username: admuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSWORD }}
          script: |
            cd /app
            docker-compose up -d
