name: Deploy

on:
  workflow_dispatch:
      inputs:
        tag:
          description: 'Docker image tag'
          required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Prepare the docker-compose tar.
        run: |
          mkdir temp
          cp docker-compose.yaml temp/
          tar -cvf deploy.tar ./temp

      - name: Copy docker-compose.yaml to server
        uses: appleboy/scp-action@master
        with:
          host: app-web527358.westeurope.cloudapp.azure.com
          username: admuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSWORD }}
          source: "deploy.tar"
          target: /home/admuser/app

      - name: Untar the file and delete temp files.
        uses: appleboy/ssh-action@master
        with:
          host: app-web527358.westeurope.cloudapp.azure.com
          username: admuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSWORD }}
          script: |
            cd /home/admuser/app
            rm docker-compose.yaml
            tar xvf deploy.tar
            cp ./temp/docker-compose.yaml docker-compose.yaml
            rm -r ./temp
            rm deploy.tar
        
      - name: Restart containers with Docker Compose
        uses: appleboy/ssh-action@master
        env:
          IMAGE_VERSION: ${{ github.event.inputs.tag }}
        with:
          host: app-web527358.westeurope.cloudapp.azure.com
          username: admuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSWORD }}
          script: |
            cd /home/admuser/app
            rm .env     
            touch .env
            echo IMAGE_VERSION=${{ github.event.inputs.tag }} >> .env
            docker-compose up -d
