name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USER: username
          MYSQL_PASSWORD: secret
          MYSQL_DATABASE: db_name
          MYSQL_ROOT_PASSWORD: passwd
          DB_PORT: 3306
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Install dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Create environment file
      run: cp .env.example .env

    - name: Generate application key
      run: php artisan key:generate

    - name: Run tests
      run: echo 'oui'

  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Connect to target server
      uses: appleboy/ssh-action@master
      with:
          host: app-web527358.westeurope.cloudapp.azure.com
          username: admuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSWORD }}

    - name: Replace environment variable in .env
      run: |
        sed -i "s/DB_HOST=127.0.0.1/DB_HOST=localhost/g" .env
      env:
        NEW_VARIABLE: ${{ secrets.NEW_VARIABLE }}

    - name: Deploy to server
      run: |
          git pull && composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist && php artisan config:clear && php artisan config:cache && php artisan key:generate && php artisan migrate --force
